.TH "panview_current/PAN/Modules/GFITS/private/c/src/GfitsLib.h" 3 "24 May 2012" "Version 13.6" "GFITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panview_current/PAN/Modules/GFITS/private/c/src/GfitsLib.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBfint\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBfuint\fP"
.br
.ti -1c
.RI "typedef long \fBflong\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBfulong\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBfint\fP"
.PP
.SS "typedef long \fBflong\fP"
.PP
.SS "typedef unsigned int \fBfuint\fP"
.PP
.SS "typedef unsigned long \fBfulong\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for GFITS from the source code.
