.TH "iteratorCol" 3 "24 May 2012" "Version 13.6" "GFITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iteratorCol \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fitsio_64.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfitsfile\fP * \fBfptr\fP"
.br
.ti -1c
.RI "int \fBcolnum\fP"
.br
.ti -1c
.RI "char \fBcolname\fP [70]"
.br
.ti -1c
.RI "int \fBdatatype\fP"
.br
.ti -1c
.RI "int \fBiotype\fP"
.br
.ti -1c
.RI "void * \fBarray\fP"
.br
.ti -1c
.RI "long \fBrepeat\fP"
.br
.ti -1c
.RI "long \fBtlmin\fP"
.br
.ti -1c
.RI "long \fBtlmax\fP"
.br
.ti -1c
.RI "char \fBtunit\fP [70]"
.br
.ti -1c
.RI "char \fBtdisp\fP [70]"
.br
.ti -1c
.RI "\fBfitsfile\fP * \fBfptr\fP"
.br
.ti -1c
.RI "void * \fBarray\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* \fBiteratorCol::array\fP"
.PP
.SS "void* \fBiteratorCol::array\fP"
.PP
.SS "char \fBiteratorCol::colname\fP"
.PP
.SS "int \fBiteratorCol::colnum\fP"
.PP
.SS "int \fBiteratorCol::datatype\fP"
.PP
.SS "\fBfitsfile\fP* \fBiteratorCol::fptr\fP"
.PP
.SS "\fBfitsfile\fP* \fBiteratorCol::fptr\fP"
.PP
.SS "int \fBiteratorCol::iotype\fP"
.PP
.SS "long \fBiteratorCol::repeat\fP"
.PP
.SS "char \fBiteratorCol::tdisp\fP"
.PP
.SS "long \fBiteratorCol::tlmax\fP"
.PP
.SS "long \fBiteratorCol::tlmin\fP"
.PP
.SS "char \fBiteratorCol::tunit\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GFITS from the source code.
