.TH "PixelFilter" 3 "24 May 2012" "Version 13.6" "GFITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PixelFilter \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fitsio_64.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "char ** \fBpath\fP"
.br
.ti -1c
.RI "char ** \fBtag\fP"
.br
.ti -1c
.RI "\fBfitsfile\fP ** \fBifptr\fP"
.br
.ti -1c
.RI "char * \fBexpression\fP"
.br
.ti -1c
.RI "int \fBbitpix\fP"
.br
.ti -1c
.RI "long \fBblank\fP"
.br
.ti -1c
.RI "\fBfitsfile\fP * \fBofptr\fP"
.br
.ti -1c
.RI "char \fBkeyword\fP [FLEN_KEYWORD]"
.br
.ti -1c
.RI "char \fBcomment\fP [FLEN_COMMENT]"
.br
.ti -1c
.RI "char ** \fBpath\fP"
.br
.ti -1c
.RI "char ** \fBtag\fP"
.br
.ti -1c
.RI "\fBfitsfile\fP ** \fBifptr\fP"
.br
.ti -1c
.RI "char * \fBexpression\fP"
.br
.ti -1c
.RI "\fBfitsfile\fP * \fBofptr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBPixelFilter::bitpix\fP"
.PP
.SS "long \fBPixelFilter::blank\fP"
.PP
.SS "char \fBPixelFilter::comment\fP"
.PP
.SS "int \fBPixelFilter::count\fP"
.PP
.SS "char* \fBPixelFilter::expression\fP"
.PP
.SS "char* \fBPixelFilter::expression\fP"
.PP
.SS "\fBfitsfile\fP** \fBPixelFilter::ifptr\fP"
.PP
.SS "\fBfitsfile\fP** \fBPixelFilter::ifptr\fP"
.PP
.SS "char \fBPixelFilter::keyword\fP"
.PP
.SS "\fBfitsfile\fP* \fBPixelFilter::ofptr\fP"
.PP
.SS "\fBfitsfile\fP* \fBPixelFilter::ofptr\fP"
.PP
.SS "char** \fBPixelFilter::path\fP"
.PP
.SS "char** \fBPixelFilter::path\fP"
.PP
.SS "char** \fBPixelFilter::tag\fP"
.PP
.SS "char** \fBPixelFilter::tag\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GFITS from the source code.
