.TH "tcolumn" 3 "24 May 2012" "Version 13.6" "GFITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcolumn \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fitsio_64.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBttype\fP [70]"
.br
.ti -1c
.RI "\fBLONGLONG\fP \fBtbcol\fP"
.br
.ti -1c
.RI "int \fBtdatatype\fP"
.br
.ti -1c
.RI "\fBLONGLONG\fP \fBtrepeat\fP"
.br
.ti -1c
.RI "double \fBtscale\fP"
.br
.ti -1c
.RI "double \fBtzero\fP"
.br
.ti -1c
.RI "\fBLONGLONG\fP \fBtnull\fP"
.br
.ti -1c
.RI "char \fBstrnull\fP [20]"
.br
.ti -1c
.RI "char \fBtform\fP [10]"
.br
.ti -1c
.RI "long \fBtwidth\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBtcolumn::strnull\fP"
.PP
.SS "\fBLONGLONG\fP \fBtcolumn::tbcol\fP"
.PP
.SS "int \fBtcolumn::tdatatype\fP"
.PP
.SS "char \fBtcolumn::tform\fP"
.PP
.SS "\fBLONGLONG\fP \fBtcolumn::tnull\fP"
.PP
.SS "\fBLONGLONG\fP \fBtcolumn::trepeat\fP"
.PP
.SS "double \fBtcolumn::tscale\fP"
.PP
.SS "char \fBtcolumn::ttype\fP"
.PP
.SS "long \fBtcolumn::twidth\fP"
.PP
.SS "double \fBtcolumn::tzero\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GFITS from the source code.
