.TH "wtbarr" 3 "24 May 2012" "Version 13.6" "GFITS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wtbarr \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fitsio_64.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBkind\fP"
.br
.ti -1c
.RI "char \fBextnam\fP [72]"
.br
.ti -1c
.RI "int \fBextver\fP"
.br
.ti -1c
.RI "int \fBextlev\fP"
.br
.ti -1c
.RI "char \fBttype\fP [72]"
.br
.ti -1c
.RI "long \fBrow\fP"
.br
.ti -1c
.RI "int \fBndim\fP"
.br
.ti -1c
.RI "int * \fBdimlen\fP"
.br
.ti -1c
.RI "double ** \fBarrayp\fP"
.br
.ti -1c
.RI "int * \fBdimlen\fP"
.br
.ti -1c
.RI "double ** \fBarrayp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double** \fBwtbarr::arrayp\fP"
.PP
.SS "double** \fBwtbarr::arrayp\fP"
.PP
.SS "int* \fBwtbarr::dimlen\fP"
.PP
.SS "int* \fBwtbarr::dimlen\fP"
.PP
.SS "int \fBwtbarr::extlev\fP"
.PP
.SS "char \fBwtbarr::extnam\fP"
.PP
.SS "int \fBwtbarr::extver\fP"
.PP
.SS "int \fBwtbarr::i\fP"
.PP
.SS "int \fBwtbarr::kind\fP"
.PP
.SS "int \fBwtbarr::m\fP"
.PP
.SS "int \fBwtbarr::ndim\fP"
.PP
.SS "long \fBwtbarr::row\fP"
.PP
.SS "char \fBwtbarr::ttype\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GFITS from the source code.
