.TH "panview_current/PAN/Modules/GUNSC/private/c/src/GU_queue.h" 3 "29 May 2012" "Version 10.2" "GUNSC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panview_current/PAN/Modules/GUNSC/private/c/src/GU_queue.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpangfits_msgbuf\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAXLEN\fP   2048"
.br
.ti -1c
.RI "#define \fBCMD\fP   1"
.br
.ti -1c
.RI "#define \fBDATA\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBpangfits_msgbuf\fP \fBqmsg_t\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CMD   1"
.PP
.SS "#define DATA   2"
.PP
.SS "#define MAXLEN   2048"
.PP
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpangfits_msgbuf\fP  \fBqmsg_t\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for GUNSC from the source code.
