CC= gcc -shared -I /usr/src/linux/include
WFLAGS = -Wall 
OFLAGS = -O
VERFLAG = -D_V14NEW_
D_SRCS = astroIIILib.c
#D_SRCS =  astroLiboldtimver.c

LIB = libastro.so.20

all: clean drivlibIII install

drivlibIII: 
	$(CC) $(WFLAGS) $(OFLAGS) $(D_SRCS) $(VERFLAG) -L ./driver_api -lsdsu -o $(LIB)

install:
	cp $(LIB) ../../../../public/c/lib/.

clean: 
	-rm -f *.so* *.o *.out *.so* ./../../AstroSDSU-II/Clib/lib/*.so* 
