.TH "pangfits_msgbuf" 3 "29 May 2012" "Version 10.2" "GUNSC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pangfits_msgbuf \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GU_queue.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBmtype\fP"
.br
.ti -1c
.RI "char \fBmsg\fP [MAXLEN]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBpangfits_msgbuf::msg\fP[MAXLEN]"
.PP
.SS "long \fBpangfits_msgbuf::mtype\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GUNSC from the source code.
